import { CustomPrompt } from '@/types'

export const DEFAULT_PROMPTS: CustomPrompt[] = [
  {
    id: 'default-prompt-code-review',
    title: 'コードレビュー',
    content: '以下のコードをレビューしてください。改善点、バグ、セキュリティ問題、パフォーマンスの最適化について指摘してください:\n\n{input}',
    description: 'コードの品質を向上させるための詳細なレビュー',
    tags: ['コード', 'レビュー', '品質'],
    category: 'coding',
    isFavorite: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'default-prompt-translation-jp-en',
    title: '日本語から英語へ翻訳',
    content: '以下の日本語テキストを自然な英語に翻訳してください。文脈を考慮し、適切な表現を使用してください:\n\n{input}',
    description: '自然で流暢な英語への翻訳',
    tags: ['翻訳', '英語', '日本語'],
    category: 'translation',
    isFavorite: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'default-prompt-summary',
    title: '要約',
    content: '以下のテキストを簡潔に要約してください。主要なポイントを箇条書きでまとめ、結論を明確にしてください:\n\n{input}',
    description: 'テキストの要点を抽出して簡潔にまとめる',
    tags: ['要約', '分析'],
    category: 'analysis',
    isFavorite: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'default-prompt-error-solution',
    title: 'エラー解決',
    content: '以下のエラーメッセージについて、考えられる原因と解決方法を提案してください:\n\n{input}',
    description: 'プログラミングエラーの診断と解決策',
    tags: ['デバッグ', 'エラー', 'トラブルシューティング'],
    category: 'coding',
    isFavorite: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'default-prompt-refactoring',
    title: 'リファクタリング提案',
    content: '以下のコードをリファクタリングしてください。可読性、保守性、パフォーマンスを改善してください:\n\n{input}',
    description: 'コードの構造と品質を改善',
    tags: ['リファクタリング', 'コード改善'],
    category: 'coding',
    isFavorite: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'default-prompt-seo',
    title: 'SEO最適化',
    content: '以下のコンテンツをSEO最適化してください。キーワード密度、メタディスクリプション、見出しの構造を改善してください:\n\n{input}',
    description: '検索エンジン最適化のための改善提案',
    tags: ['SEO', 'マーケティング', 'ウェブ'],
    category: 'writing',
    isFavorite: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'default-prompt-creative-writing',
    title: '創造的な文章作成',
    content: '以下のトピックについて、創造的で魅力的な文章を書いてください:\n\n{input}',
    description: '創造性豊かな文章の生成',
    tags: ['ライティング', '創造性'],
    category: 'creative',
    isFavorite: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'default-prompt-business-email',
    title: 'ビジネスメール作成',
    content: '以下の内容で、プロフェッショナルなビジネスメールを作成してください:\n\n{input}',
    description: 'フォーマルで効果的なビジネスコミュニケーション',
    tags: ['ビジネス', 'メール', 'コミュニケーション'],
    category: 'writing',
    isFavorite: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]